### ISSUE TITLE
Version 2.3.1

### ISSUE THREAD

**Issue by EmViKay** [aws-solutions/aws-waf-security-automations#114]
I have deployed version 2.3.0
I am going to update Version 2.3.1.
Have an error:

2020-01-03 14:38:03 UTC+0200 | CheckRequirements | UPDATE_FAILED | Modifying service token is not allowed.
-- | -- | -- | --

2020-01-03 14:38:04 UTC+0200 | AWSWAFSecurityAutomations | UPDATE_ROLLBACK_IN_PROGRESS | The following resource(s) failed to update: [CheckRequirements].
-- | -- | -- | --

Can someone help me?

**Comment by casper5822** [comment]
Same error for me.

**Comment by krymen** [comment]
Same here.

**Comment by EmViKay** [comment]
any updates?

**Comment by curtismorte** [comment]
If you follow the events for the CloudFormation Stack, you will see what service is being worked on / created and then you can use additional tools to debug further from there.

**For example, the event "Logical ID" you're looking at is:** CheckRequirements

The events leading up to your error (listed below by Logical ID) should be:

1. [NAME-OF-STACK]
1. LambdaRoleHelper
1. LambdaRoleHelper
1. LambdaRoleHelper
1. Helper
1. Helper
1. Helper
1. CheckRequirements
1. CheckRequirements

> If you launch the stack successfully you should see 3 events that have a Logical ID of "CheckRequirements" with the third event's status being "CREATE_COMPLETE".

Since you're likely failing at the first or second event with Logical ID "CheckRequirements" that's where you should begin your inspection.

If you have CloudTrail enabled, I recommend starting there and looking at events generated by your user / role which is responsible for creating the stack. This will give you some more details / logs which you can inspect to find the source of the issue.

If you don't have CloudTrail enabled, re-create the stack (knowing it will fail), and then inspect the events for CloudTrail.

**Comment by ariel-chwat** [comment]
I also failed to update an existing stack to the new version. did anyone managed to resolve it?

**Comment by curtismorte** [comment]
@ariel-chwat If you're updating an existing stack, using the same S3 bucket parameter, then you will run into a problem with the event that was already created for the bucket. The name of that event is "Call Log Parser" and both the Name and Filter attributes are what cause the problem.

I deleted the event (taking a quick screenshot of the settings to add in case of another problem), and the launched the new stack.

**Comment by aijunpeng** [comment]
We have deprecated WAF classic version <=2.3.3. Closing this old issue.
